INSERT INTO categories (resource_id, category)
VALUES (1, 'Food'),
(2, 'Hobbies'),
(3, 'Hobbies'),
(4, 'Health'),
(5, 'Education'),
(6, 'Education'),
(7, 'Education'),
(8, 'Health'),
(9, 'Food'),
(10, 'Hobbies'),
(11, 'Hobbies'),
(12, 'Education'),
(13, 'Food'),
(14, 'Hobbies'),
(15, 'Health'),
(16, 'Food'),
(17, 'Health'),
(18, 'Hobbies'),
(19, 'Health'),
(20, 'Food');
