INSERT INTO comments (user_id, resource_id, date_created, comment)
VALUES(1, 1, '2020-08-28', 'Bacon ipsum dolor amet kielbasa tail fatback swine porchetta sirloin t-bone tongue drumstick kevin meatloaf.'),
(2, 1, '2020-09-01', 'I''m baby hoodie keffiyeh bespoke kitsch kinfolk hella. Tofu bespoke literally blog.'),
(3, 1, '2020-10-01', 'Subway tile chartreuse kitsch gentrify locavore. Ethical franzen chicharrones hexagon literally succulents kogi copper mug adaptogen.'),
(1, 2, '2020-08-04', ' La croix migas fanny pack seitan kickstarter quinoa farm-to-table plaid four dollar toast whatever.'),
(2, 2, '2020-09-03', 'Blue bottle vape banjo mixtape franzen, marfa pickled put a bird on it iPhone migas lumbersexual neutra microdosing +1.'),
(3, 2, '2020-10-12', 'Chartreuse tilde dreamcatcher williamsburg kinfolk.'),
(1, 3, '2020-08-03', 'Mixtape tilde cold-pressed artisan literally etsy bespoke roof party glossier before they sold out put a bird on it tousled.'),
(2, 3, '2020-09-11', 'Tumblr sustainable bespoke artisan post-ironic, hell of banh mi pinterest migas fixie af 8-bit try-hard ennui.'),
(3, 3, '2020-09-14', 'Synth lyft jianbing selfies pug crucifix.'),
(1, 4, '2020-08-30', 'Trust fund tbh fingerstache raw denim, XOXO lumbersexual drinking vinegar distillery readymade tilde.'),
(2, 4, '2020-09-15', 'Gastropub swag chambray pop-up taxidermy crucifix scenester schlitz neutra chillwave knausgaard pour-over street art raclette XOXO.'),
(3, 4, '2020-10-15', 'Mixtape lomo gastropub tumeric pork belly, DIY literally trust fund yuccie palo santo air plant.'),
(1, 5, '2020-08-28', 'Knausgaard gentrify locavore banjo selvage lomo hoodie tbh microdosing organic vegan.'),
(2, 5, '2020-09-01', 'Slow-carb kitsch tacos pabst portland, craft beer paleo actually food truck kombucha raclette meggings tumblr blog church-key.'),
(3, 5, '2020-10-04', 'Whatever shaman raclette tbh skateboard before they sold out, four loko messenger bag subway tile adaptogen meggings chambray.'),
(1, 6, '2020-08-04', 'Four loko echo park letterpress thundercats pork belly.'),
(2, 6, '2020-09-05', 'Cloud bread distillery salvia, tumeric brooklyn yr narwhal. Normcore subway tile hammock tumeric.'),
(3, 6, '2020-10-06', 'Poke umami beard XOXO williamsburg venmo.'),
(1, 7, '2020-08-20', 'Flannel lomo humblebrag, whatever brunch roof party mixtape kickstarter palo santo cornhole kitsch vexillologist tattooed artisan.'),
(2, 7, '2020-09-05', 'Kogi mustache crucifix meh chicharrones try-hard copper mug franzen actually, freegan tousled yr keffiyeh.'),
(3, 7, '2020-10-01', 'Bespoke freegan selfies, tumeric sustainable tofu keytar shoreditch aesthetic.'),
(1, 8, '2020-08-09', 'Meditation leggings fashion axe la croix art party, marfa shoreditch.'),
(2, 8, '2020-08-28', 'Gluten-free woke fanny pack VHS blog dreamcatcher affogato whatever heirloom aesthetic.'),
(3, 8, '2020-08-01', 'Dummy text? More like dummy thicc text, amirite?'),
(1, 9, '2020-09-30', 'I''m baby butcher gentrify leggings kitsch, mixtape disrupt keffiyeh cronut direct trade shoreditch meditation irony DIY venmo fam.'),
(2, 9, '2020-08-09', 'Chillwave deep v 8-bit cornhole shoreditch, actually hell of.'),
(3, 9, '2020-08-01', 'Messenger bag whatever seitan direct trade.'),
(1, 10, '2020-10-10', 'Cray waistcoat coloring book drinking vinegar pour-over heirloom.'),
(2, 10, '2020-08-28', 'Man bun hammock selvage palo santo bicycle rights DIY heirloom vexillologist knausgaard beard meditation squid vape roof party.'),
(3, 10, '2020-09-04', 'Tofu brooklyn iceland sriracha prism tbh, skateboard selfies heirloom venmo.'),
(1, 11, '2020-10-03', 'Bitters occupy direct trade fam taxidermy.'),
(2, 11, '2020-10-01', 'Williamsburg pour-over helvetica succulents cray tumblr DIY cronut man bun shabby chic gluten-free wolf pug enamel pin.'),
(3, 11, '2020-08-20', 'Echo park twee helvetica bicycle rights, hot chicken vegan umami af authentic aesthetic quinoa mlkshk iPhone.'),
(1, 12, '2020-09-06', 'Readymade taiyaki ennui jean shorts.'),
(2, 12, '2020-08-20', 'Dreamcatcher cronut cold-pressed literally post-ironic viral poutine ugh franzen.'),
(3, 12, '2020-10-01', 'Kickstarter pour-over beard normcore hoodie you probably haven''t heard of them lomo lo-fi pickled vinyl mumblecore meggings.'),
(1, 13, '2020-08-29', 'Quinoa enamel pin twee, poke plaid listicle four dollar toast bicycle rights flexitarian readymade tousled af 3 wolf moon marfa yuccie.'),
(2, 13, '2020-09-09', 'Butcher williamsburg bespoke semiotics four loko poke yuccie franzen four dollar toast deep v brunch kitsch raw denim.'),
(3, 13, '2020-09-11', 'Slow-carb normcore you probably haven''t heard of them lyft scenester pork belly actually green juice seitan, fam shoreditch.'),
(1, 14, '2020-08-17', 'Pour-over tumeric succulents, jean shorts pabst tattooed ennui art party chicharrones celiac tousled four dollar toast irony.'),
(2, 14, '2020-09-10', '3 wolf moon thundercats cray, craft beer asymmetrical woke cardigan slow-carb. Craft beer kale chips pabst cardigan cold-pressed.'),
(3, 14, '2020-08-19', 'Distillery truffaut hella chartreuse pop-up brooklyn craft beer snackwave lomo.'),
(1, 15, '2020-09-09', 'Ugh retro enamel pin, man braid scenester narwhal iPhone green juice four dollar toast blog deep v brunch hammock neutra.'),
(2, 15, '2020-10-11', 'Trust fund cold-pressed crucifix, artisan umami cronut yuccie gastropub fam.'),
(3, 15, '2020-09-15', 'Authentic taiyaki semiotics, jean shorts live-edge raw denim try-hard.'),
(1, 16, '2020-10-04', 'Lomo banjo semiotics swag. Kogi brunch adaptogen put a bird on it jean shorts cliche.'),
(2, 16, '2020-10-01', 'Crucifix bespoke fingerstache gentrify art party vegan, hot chicken lomo tattooed stumptown vinyl quinoa poke.'),
(3, 16, '2020-08-05', 'Four dollar toast woke chartreuse prism bushwick craft beer brooklyn keytar bicycle rights put a bird on it quinoa raw denim swag.'),
(1, 17, '2020-08-28', 'Lyft bespoke pour-over, paleo gochujang palo santo pop-up ugh vexillologist chambray.'),
(2, 17, '2020-09-15', 'Palo santo tumeric vinyl beard, activated charcoal man braid VHS.'),
(3, 17, '2020-10-02', 'Heirloom beard salvia gentrify, venmo adaptogen you probably haven''t heard of them hammock semiotics hell of cardigan biodiesel next le.'),
(1, 18, '2020-08-09', 'Blog umami farm-to-table af, vape salvia adaptogen migas iPhone retro. Trust fund viral swag drinking vinegar.'),
(2, 18, '2020-08-07', 'Kogi kale chips mixtape, etsy adaptogen chambray ramps.'),
(3, 18, '2020-08-01', 'Yr vegan street art banh mi.'),
(1, 19, '2020-10-01', 'Echo park locavore art party, fixie activated charcoal hexagon put a bird on it williamsburg ugh shoreditch viral subway tile tilde.'),
(2, 19, '2020-09-17', 'Tote bag paleo flexitarian, mlkshk cornhole mustache woke ethical vice semiotics la croix offal seitan hammock. Bespoke mixtape kinfolk.'),
(3, 19, '2020-08-28', 'Glossier woke tote bag messenger bag mlkshk cardigan raw denim bitters whatever listicle sriracha you probably haven''t heard of them.'),
(1, 20, '2020-09-10', 'Brooklyn cliche gentrify, hoodie hammock occupy tofu air plant 90''s.'),
(2, 20, '2020-08-28', 'IPhone bushwick copper mug letterpress hell of, sriracha meditation blue bottle disrupt vegan cardigan mlkshk austin fam.'),
(3, 20, '2020-08-06', 'Microdosing slow-carb edison bulb brunch.');
