INSERT INTO resources (url, user_id, title, description, date_created, media_type)
VALUES ('https://www.youtube.com/watch?v=iu36cQEm2Qs', 1, 'How to Bake a Cake Like a Pro', 'Easy instructional video on how to bake a cake', '2020-07-25', 'video'),
('https://www.youtube.com/embed/4Ouobcj5dBo', 1, '5 Tips to Survive Flat and Narrow Runs', 'Instructional snowboard video for beginners', '2020-07-03', 'video'),
('https://i.pinimg.com/736x/99/70/fa/9970fad1fa4f8c1891b8555cc4830229.jpg', 1, 'Step by Step Crochet Stitch Tutorial', 'A beginners guide to crocheting', '2020-06-30', 'image'),
('https://www.youtube.com/embed/AjfXHe7ZCDw', 2, 'Olympic Weightlifting 101', 'How to snatch -  a video guide', '2020-07-31', 'video'),
('https://www.youtube.com/embed/McZW0iDsZns', 3, 'Learn Chinese for Beginners', 'Beginner Chinese Lesson 1 - Introductions', '2020-03-16', 'video'),
('https://www.youtube.com/embed/QOpQf3fi2N4', 3, 'Learn Chinese in 30 minutes', 'Basic Chinese for Beginners', '2020-05-03', 'video'),
('https://en.wikipedia.org/wiki/Chinese_characters', 3, 'Chinese Characters', 'Wikipedia article on Chinese characters', '2020-07-12', 'article'),
('https://www.healthline.com/nutrition/how-to-count-macros', 2, 'How to Count Macros: A Step-By-Step Guide', 'Tips on diet and nutrition tracking', '2020-07-10', 'article'),
('https://www.theclevercarrot.com/2014/01/sourdough-bread-a-beginners-guide/', 1, 'Sourdough Bread: A Beginner''s Guide', 'Bake bread like a pro!', '2020-06-10', 'article'),
('https://www.youtube.com/embed/JMQGtch40G0', 2, 'Acting Lessons For Beginners', 'Learn how to act from a professional!', '2020-05-20', 'video'),
('https://www.youtube.com/embed/K-f6QOD9R0M', 1, 'Top 10 Deer Hunting Mistakes', 'Make sure not to do these things if you are learning to hunt!', '2020-04-10', 'video'),
('https://www.youtube.com/embed/WKuNWrxuJ9g', 3, 'How to Learn to Code', 'What''s the best way to learn programming?  Watch this video to find out!', '2020-07-30', 'video'),
('https://www.mccormick.com/recipes/breakfast-brunch/quick-and-easy-french-toast', 1, 'Quick and Easy French Toast', 'Step by step recipe for a delicious breakfast!', '2020-06-18', 'article'),
('https://www.youtube.com/embed/OpC53Tjwfyg', 1, '5 Tips for Beginner Snowboard Jumps', 'These five tips will help you to learn with good technique, at your own pace, and in a way that keeps you safe.', '2020-07-31', 'video'),
('https://www.shape.com/fitness/training-plans/beginners-guide-running-5k', 2, 'How to Train for a 5k', 'A step-by-step guide for beginners who want to run 5k!', '2020-06-12', 'article'),
('https://www.foodandwine.com/how/easy-french-recipes-beginner-cook', 1, '16 French Recipes Every Beginner Cook Should Master', 'French cooking techniques for absolute beginners', '2020-05-30', 'article'),
('https://www.healthline.com/nutrition/best-ways-to-get-abs', 2, 'Best Ways to Get Abs', '8 simple ways to achieve six-pack abs quickly and safely', '2020-07-01', 'article'),
('https://www.wired.co.uk/article/master-rock-paper-scissors', 3, 'How to Master Rock-Paper-Scissors', 'Tips and strategies from a true master - why rock is for newbies!', '2020-06-27', 'article'),
('https://i.pinimg.com/564x/c3/de/ff/c3deff5675b0577218c3608fd40161f2.jpg', 2, 'Macro Cheat Sheet', 'Quick and easy macro reference', '2020-06-02', 'image'),
('https://www.gardeninggiftsdirect.com/wp-content/uploads/2018/03/GGD-14-HGC.jpg', 1, 'Herb Guide to Cooking', 'Great poster for referencing herb-food pairings', '2020-07-16', 'image');

